import type { LeadStatus } from "@/lib/api/leads";

export const CALL_NOTE_TEMPLATE_KEYS = [
  "NO_ANSWER",
  "VOICEMAIL_LEFT",
  "WRONG_NUMBER",
  "ASKED_CALLBACK_LATER",
  "REQUESTED_MORE_INFO",
  "SENT_WHATSAPP_INFO",
  "REQUESTED_QUOTE",
  "NOT_INTERESTED_PRICE",
  "NOT_INTERESTED_NO_NEED",
  "DO_NOT_CALL_AGAIN",
  "ALREADY_CUSTOMER",
  "PAYMENT_CONFIRMED",
  "CUSTOMER_CANCELLED",
] as const;

export type CallNoteTemplateKey = (typeof CALL_NOTE_TEMPLATE_KEYS)[number];

export const CALL_NOTE_TEMPLATES_BY_STATUS: Record<LeadStatus, CallNoteTemplateKey[]> = {
  NEW: ["NO_ANSWER", "VOICEMAIL_LEFT", "WRONG_NUMBER", "ASKED_CALLBACK_LATER"],
  CONTACTED: ["NO_ANSWER", "VOICEMAIL_LEFT", "ASKED_CALLBACK_LATER", "REQUESTED_MORE_INFO"],
  INTERESTED: ["REQUESTED_MORE_INFO", "SENT_WHATSAPP_INFO", "REQUESTED_QUOTE", "ASKED_CALLBACK_LATER"],
  NOT_INTERESTED: ["NOT_INTERESTED_PRICE", "NOT_INTERESTED_NO_NEED", "ALREADY_CUSTOMER", "DO_NOT_CALL_AGAIN"],
  CLOSED_SALE: ["PAYMENT_CONFIRMED"],
  CANCELLED: ["CUSTOMER_CANCELLED"],
};
